<a href="https://colab.research.google.com/github/GabrielLRizzo/Aula_02/blob/main/aula_02_classificacao_reg_logistica_Iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Aplicação de regressão logística ao *dataset* Iris

Documentação: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

Nesta atividade, vamos aplicar a regressão logística -- um modelo de classificação linear -- ao *dataset* Iris.


        

## Roteiro:

1. Carregar os pacotes usuais de manipulação de dados e os pacotes para treinamento e avaliação dos modelos.
2. Carregar o *dataset*.
3. Preparar o *dataset*:
  *  Em que formato devem estar os dados de entrada e de saída para o treinamento do classificador?
4. Particionar o *dataset* em treinamento e teste.
  * https://scikit-learn.org/stable/api/sklearn.model_selection.html
5. Treinar a regressão logística.
6. Aplicar o modelo treinado ao conjunto de teste e computar diferentes métricas de desempenho.
  * https://scikit-learn.org/stable/api/sklearn.metrics.html

### Passo 1: carregar os pacotes

In [7]:
""" Importando pacotes usuais """

import numpy as np
import pandas as pd
import matplotlib as mp
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import seaborn as sns

### Passo 2: carregar o *dataset*

In [4]:
#Carregando o dataset Iris na forma de um Bunch
iris = load_iris(as_frame=True)

#DataFrame único (inclui atributos e rótulos)
df = iris.frame

labels = {0: 'setosa', 1: 'versicolor',
            2: 'virginica'}

# Acrescenta a coluna 'labels' mapeando os valores de 'target' conforme o dicionário criado
df['labels'] = df['target'].map(labels)

#isola os nomes das classes
class_names = df['labels'].unique()

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target,labels
0,5.1,3.5,1.4,0.2,0,setosa
1,4.9,3.0,1.4,0.2,0,setosa
2,4.7,3.2,1.3,0.2,0,setosa
3,4.6,3.1,1.5,0.2,0,setosa
4,5.0,3.6,1.4,0.2,0,setosa


### Passo 3: preparar o *dataset*

Sabemos que o conjunto Iris como um todo possui 150 amostras caracterizadas por 4 atributos numéricos e acompanhadas de um rótulo numérico que identifica a espécie.

| Rótulo | Classe |
| ----- | ----- |
| 0 | Setosa |
| 1 | Versicolor|
| 2 | Virginica |

In [6]:
""" Preparar o dataset para poder ser utilizado no treinamento de modelos de machine learning """
#Extrai do dataframe um array com as 150 amosras representadas por seus 4 atributos
X = df.iloc[:, :4].values
#Extrai do Dataframe um array com os rotulos
y = df["target"].values


print(f'Dataset de entrada: {X.shape}')
print(f'Dataset de saída: {y.shape}')

Dataset de entrada: (150, 4)
Dataset de saída: (150,)


### Passo 4: particionar o *dataset* em treinamento e teste

**Recomendação:** exiba as dimensões dos conjuntos de treinamento e teste após a divisão.

In [10]:
""" Particionamento do dataset em treinamento e teste"""
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size= 0.2, random_state= 42)

print(f'X_treino: {X_treino}')
print(f'X_teste: {X_teste}')
print(f'y_treino: {y_treino}')
print(f'y_teste: {y_teste}')




X_treino: [[4.6 3.6 1.  0.2]
 [5.7 4.4 1.5 0.4]
 [6.7 3.1 4.4 1.4]
 [4.8 3.4 1.6 0.2]
 [4.4 3.2 1.3 0.2]
 [6.3 2.5 5.  1.9]
 [6.4 3.2 4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.2 4.1 1.5 0.1]
 [5.8 2.7 5.1 1.9]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [5.4 3.9 1.3 0.4]
 [5.4 3.7 1.5 0.2]
 [5.5 2.4 3.7 1. ]
 [6.3 2.8 5.1 1.5]
 [6.4 3.1 5.5 1.8]
 [6.6 3.  4.4 1.4]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [7.6 3.  6.6 2.1]
 [5.6 3.  4.5 1.5]
 [5.1 3.5 1.4 0.2]
 [7.7 2.8 6.7 2. ]
 [5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.1 3.3 1.7 0.5]
 [5.6 2.7 4.2 1.3]
 [5.1 3.4 1.5 0.2]
 [5.7 3.  4.2 1.2]
 [7.7 3.8 6.7 2.2]
 [4.6 3.2 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.7 2.5 5.  2. ]
 [5.5 4.2 1.4 0.2]
 [6.  3.  4.8 1.8]
 [5.8 2.7 5.1 1.9]
 [6.  2.2 4.  1. ]
 [5.4 3.  4.5 1.5]
 [6.2 3.4 5.4 2.3]
 [5.5 2.3 4.  1.3]
 [5.4 3.9 1.7 0.4]
 [5.  2.3 3.3 1. ]
 [6.4 2.7 5.3 1.9]
 [5.  3.3 1.4 0.2]
 [

### Passo 5: treinar o modelo de regressão logística

In [ ]:
""" Treinamento da regressão logística """

#Recomendação:** finalizado o treinamento, confira os parâmetros do modelo treinado.

linear_regression = LogisticRegression(penalty='l2')

#Treinamento

#Conferindo os parâmetros do modelo



### Passo 6: aplique o modelo treinado ao conjunto de teste e obtenha algumas métricas de avaliação

In [ ]:
""" Obtém a matriz de confusão e outras métricas de desempenho no conjunto de teste """

...
...



### Extra: mostre as probabilidades estimadas para todas as amostras do conjunto de teste junto com os rótulos estimados e reais.

In [ ]:
""" Obtenha as probs. estimadas para o conjunto de teste """

...
...